[package]
name = "failure_ext"
version = "0.2.0"
authors = ["Sergey Parshukov <codedby@bugman.me>"]
description = "Sugar for the failure crate"
license = "MIT"
publish = false

[dependencies]
failure = "0.1.1"
