[package]
name = "future_rust"
version = "0.3.0"
authors = ["Sergey Parshukov <codedby@bugman.me>"]
description = "Future-compatibility with std Rust"
license = "MIT"
publish = false

[dependencies]
try_from = "0.2.2"
